Status Quo

diff --git a/tools/scripts/parseTodeitOutput b/tools/scripts/parseTodeitOutput
--- a/tools/scripts/parseTodeitOutput
+++ b/tools/scripts/parseTodeitOutput
@@ -1,6 +1,5 @@
 #!/bin/bash
 while IFS= read line; do
-    echo "$line"
-    echo "$line" | grep -E "errors while loading|Press 'Proceed' to continue\." && echo "found error" && exit 7;
+    echo "$line" | grep -E "errors while loading|Press 'Proceed' to continue\." && exit 7;
 done
 exit 0;
